### ISSUE TITLE
Wrong calculation for vaccine dose

### ISSUE THREAD

**Issue by 36wish** [ryan-mooore/nz-covid19-tracker#1]
https://github.com/ryan-mooore/nz-covid19-tracker/blob/56fefa182ac69903b664d01a57e379666c671bae/src/tweets/COVID-19:%20Vaccine%20data/doses_update.py#L27

I don't think this is right. `any_dose` (Total dose administered) could've been a first dose or a second dose. I think it should be `only_first`.

**Comment by kiwirm** [comment]
Thanks for picking this up. I've avoided using "Total doses administered" altogether as it is ambiguous to count people from total doses.
